### ISSUE TITLE
[IP] Check database collation

### ISSUE THREAD

**Issue by sebastian-meyer** [kitodo/kitodo-production#27]
Currently Goobi.Production uses "latin1_swedish_ci" as database collation. Maybe it would be better to use "utf8_bin"?

**Comment by matthias-ronge** [comment]
This [has been solved](https://github.com/kitodo/kitodo-production/blob/master/Kitodo-DataManagement/src/main/resources/db/migration/V2_12__Convert_encoding_of_tables_to_utf8.sql).

**Comment by henning-gerhardt** [comment]
@matthias-ronge : This is still not solved for 2.x only for 3.x. In 2.x it depends how old your current database is or what the default collation is set on the database system for new installations.

**Comment by matthias-ronge** [comment]
Do you want to leave open all issues that are not fixed in any old versions? Or is there a reason that this needs to be changed specifically in legacy 2.x?

**Comment by sebastian-meyer** [comment]
I think this should remain open at least until migrations are done, because old legacy collations could become a problem when migrating the database. Maybe it'd be easier to first fix this issue in 2.x before migrating to 3.x because then everyone uses the same collation and that would make migration easier?

**Comment by matthias-ronge** [comment]
I agree. We will wait for the results of the migration workshop next week. Migration scripts take these basic database corrections into the account (name all tables in English, charset and collation settings, etc.) at the beginning so I think there will be no problem. I suspect that re-sorting the database migration steps is unpopular and also not necessary.

**Comment by matthias-ronge** [comment]
We had no problem with the character sets in the migration workshop. However, they were already set to utf-8 on the test migration system, which is why this is not very meaningful.

**Comment by matthias-ronge** [comment]
I will close this ticket as long as there are no errors.
