### ISSUE TITLE
Desktop should select the correct process

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3296]
From the desktop page, when you open a process in the metadata editor, the wrong process opens.

**Goal:** The selected process should be opened. (The same should apply to deletion; needs review)

**Comment by solth** [comment]
Are you sure you are using the current version of the software? The reason for this bug is the same as #3194 and has been resolved some time ago.

**Comment by matthias-ronge** [comment]
I could reproduce the problem with version [0a8fef06a4fbce052a568fd82b875d7a2e763ae8](https://github.com/kitodo/kitodo-production/tree/0a8fef06a4fbce052a568fd82b875d7a2e763ae8) which [is up to date with the changes you mentioned](https://github.com/kitodo/kitodo-production/compare/0a8fef06a4fbce052a568fd82b875d7a2e763ae8...47874d4382c2a5dde4f614d8df78308b4a05e45f).

**Comment by matthias-ronge** [comment]
I can still reproduce the problem with version [81a199d4f77aa4e660fea5d46776804dc142f45e](https://github.com/kitodo/kitodo-production/tree/81a199d4f77aa4e660fea5d46776804dc142f45e).
