### ISSUE TITLE
Adjustments on filter menu "Add filter"

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3511]
### Problems
1 The menu "Add filter" is shown, when the "enter key" is used. That is confusing, when the "enter key" is used to start the search/filter, because the user does not know, what to do with that. 
It is ok, when the filter is activated by the button on the right side of the filter-box. 

<del>2 Added filters cannot be deleted by the garbage can-icon.<del>

2022-09-01 (@andre-hohmann): The deletion of filters works now

### Solution
1 Deactivation  the "Add filter"-menu by enter-key

<del>2 Activation of the garbage can-icon to enable the deletion of added filters.<del>

2022-09-01 (@andre-hohmann): The deletion of filters works now

**Comment by solth** [comment]
> 2 Activation of the garbage can-icon to enable the deletion of added filters.

Fixed by #4349

**Comment by andre-hohmann** [comment]
Update; 

Problem 1 is still present: 
> 1 The menu "Add filter" is shown, when the "enter key" is used. That is confusing, when the "enter key" is used to start the search/filter, because the user does not know, what to do with that.
It is ok, when the filter is activated by the button on the right side of the filter-box.
**Solution**: Deactivation the "Add filter"-menu by enter-key

Problem 2: 
The deleted filters are shown until the user logs off and in again. Adding a filter is also completed only after log off/log in. 
I am sure that at least adding a filter has once worked correctly.

**Comment by solth** [comment]
> Problem 2:
> The deleted filters are shown until the user logs off and in again. Adding a filter is also completed only after log off/log in.
> I am sure that at least adding a filter has once worked correctly.

You are right. Actually _both_ functions (adding _and_ deleting filters) were applied immediatley, so I am not sure why this stopped working again. I will take a look at it and report my findings here.
